name: Propagate Echweb Changes
run-name: ${{ github.actor }} Propagating Echweb Changes
on:
  push:
    branches:
      - master
jobs:
  build-mcro_de:
    permissions:
      contents: write
      pull-requests: write
    uses: microdee/echweb-mcrode/.github/workflows/publish.yml@master
# build-nyulga_com:
#  permissions:
#    contents: write
#    pull-requests: write
#   uses: microdee/echweb-mcrode/.github/workflows/publish.yml@master
#