name: Publish Echweb Site
on:
  workflow_call:
    inputs:
      content-repo:
        required: true
        type: string
      target-domain:
        required: true
        type: string
      target-domain_var:
        required: true
        type: string
      target-repo:
        required: true
        type: string
    secrets:
      PAGES_DEPLOY_TOKEN:
        required: true
run-name: Publishing ${{ inputs.target-domain }}
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - 
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
      -
        name: Checkout Echweb
        uses: actions/checkout@v4
        with:
          repository: microdee/echweb
          lfs: true
      -
        name: Checkout content from ${{ inputs.content-repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.content-repo }}
          path: ./content
          lfs: true
      -
        name: Install / Prepare / Build
        run: ./build.sh install prepare build
      -
        name: Checkout target repo ${{ inputs.target-repo }}
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target-repo }}
          fetch-depth: 0
          path: dist_git
          lfs: true
          token:  "${{ secrets.PAGES_DEPLOY_TOKEN }}"
      -
        name: Move .git folder to dist
        run: |
          mv ./dist_git/.git ./dist/.git
          rm ./dist_git -r
      -
        name: Push changes to ${{ inputs.target-repo }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: publish from gh actions
          repository: dist
          commit_user_name: microdee
          commit_user_email: m@mcro.de
          commit_author: David Morasz <m@mcro.de>
          status_options: '--untracked-files=all'
          skip_fetch: true
          skip_checkout: true


